{{- if .Values.EnvVars.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello.fullname" . }}
data:
 {{- range $key,$value := .Values.env }}
 {{ $key }}: {{ $value | quote }}
 {{- end }}
{{- end }}
