{{- if .Values.services }}
{{- range $.Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
  {{- if $.Values.fullnameOverride }}
    fullname: {{ $.Values.fullnameOverride | quote }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- if $.Values.fullnameOverride }}
    fullname: {{ $.Values.fullnameOverride | quote }}
  {{- end }}
{{- end }}
{{- end }}
---